routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\MainController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', MainController::class);
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('page/{id}', [App\Http\Controllers\Admin\PostController::class, 'show'])->name('page');
Route::middleware(['role:admin'])->prefix('admin_panel')->group(function () {
   Route::get('/', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('homeAdmin');
   Route::resource('tag', TagController::class);
   Route::resource('category', CategoryController::class);
   Route::resource('post', PostController::class);
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentTaggable\Taggable;

class Post extends Model
{
    use HasFactory;
    use Taggable;

    public function category()
    {
        return $this->belongsTo(Category::class, 'cat_id');
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Post;
use App\Models\Category;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::orderBy('created_at', 'DESC')->get();

        return view('admin.post.index', [
            'posts' => $posts
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::orderBy('created_at', 'DESC')->get();

        return view('admin.post.create', [
            'categories' => $categories
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $post = new Post();
        $post->title = $request->title;
        $post->img = $request->img;
        $post->text = $request->text;
        $post->cat_id = $request->cat_id;
        $post->save();

        return redirect()->back()->withSuccess('Статья была успешно добавлена');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::findOrFail($id);
        $previous_page = Post::where('id', '>', $post->id)->first();
        $next_page = Post::where('id', '<', $post->id)->first();
        return view('post', [
          'post' => $post,
          'previous_page' => $previous_page,
          'next_page' => $next_page,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categories = Category::orderBy('created_at', 'DESC')->get();

        return view('admin.post.edit', [
            'categories' => $categories,
            'post' => $post,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $post->title = $request->title;
        $post->img = $request->img;
        $post->text = $request->text;
        $post->cat_id = $request->cat_id;
        $post->status = $request->status;
        $post->save();

        return redirect()->back()->withSuccess('Статья была успешно обновлена');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();
        return redirect()->back()->withSuccess('Статья была успешно удалена!');
    }
}

resources/views/admin/post/create.blade.php
@extends('layouts.admin_layout')
@section('title', 'Добавить cтатью')
@section('content')

<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">Добавить cтатью</h1>
        </div><!-- /.col -->
      </div><!-- /.row -->
        @if (session('success'))
            <div class="alert alert-success" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
            </div>
        @endif
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
            <div class="card card-primary">
                <!-- form start -->
                <form action="{{ route('post.store') }}" method ="POST">
                  @csrf
                  <div class="card-body">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Название</label>
                      <input type="text" name="title" class="form-control" id="exampleInputEmail1" placeholder="Введите название статьи" required>
                    </div>
                    <div class="form-group">
                            <!-- select -->
                        <div class="form-group">
                            <label>Выберите категорию</label>
                            <select name="cat_id" class="form-control" required>
                                @foreach ($categories as $category)
                                <option value="{{ $category['id'] }}">{{ $category['title'] }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <textarea name="text" class="editor"></textarea>
                      </div>
                  </div>

                  <div class="form-group mx-3">
                    <label for="feature_image">Изображение статьи</label>
                    <img src="" alt="" class="img-uploaded" style="display: block; width: 300px">
                    <input type="text" name="img" class="form-control" id="feature_image" name="feature_image" value="" readonly>
                    <a href="" class="popup_selector" data-inputid="feature_image">Выбрать изображение</a>
                  </div>
              </div>
                  <!-- /.card-body-->
                  <div class="form-group">
                    <label>Multiple</label>
                    <select class="select2" name="tag_ids[]" multiple="multiple" data-placeholder="Select a State" style="width: 100%;">
                      <option value="{{ $tag->id }}">{{ $tag->title }}</option>
                    </select>
                  </div>

                  <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Добавить</button>
                  </div>
                </form>
              </div>
        </div>
     </div>
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->
@endsection

resources/views/admin/post/edit.blade.php
@extends('layouts.admin_layout')
@section('title', 'Редактировать cтатью')
@section('content')

<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">Редактировать cтатью: {{ $post['title'] }}</h1>
        </div><!-- /.col -->
      </div><!-- /.row -->
        @if (session('success'))
            <div class="alert alert-success" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
            </div>
        @endif
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
            <div class="card card-primary">
                <!-- form start -->
                <form action="{{ route('post.update', $post['id']) }}" method ="POST">
                  @csrf
                  @method('PUT')
                  <div class="card-body">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Название</label>
                      <input type="text" value="{{ $post['title'] }}" name="title" class="form-control" id="exampleInputEmail1" placeholder="Введите название статьи" required>
                    </div>
                    <div class="form-group">
                            <!-- select -->
                        <div class="form-group">
                            <label>Выберите категорию</label>
                            <select name="cat_id" class="form-control" required>
                                @foreach ($categories as $category)
                                <option value="{{ $category['id'] }}" @if($category['id'] == $post['cat_id']) selected @endif>{{ $category['title'] }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <textarea name="text" class="editor">{{ $post['text'] }}</textarea>
                      </div>
                    
                    <div class="form-group">
                      <label>Выберите статус</label>
                      <select name="status" class="form-control" required>
                          <option value="1">Active</option>
                          <option value="0">Disable</option>
                      </select>
                    </div>
                  </div>

                  <div class="form-group mx-3">
                    <label for="feature_image">Изображение статьи</label>
                    <img src="{{ $post['img'] }}" alt="" class="img-uploaded" style="display: block; width: 300px">
                    <input type="text" value="{{ $post['img'] }}" name="img" class="form-control" id="feature_image" name="feature_image" value="" readonly>
                    <a href="" class="popup_selector" data-inputid="feature_image">Выбрать изображение</a>
                  </div>
              </div>
                  <!-- /.card-body -->

                  <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                  </div>
                </form>
              </div>
        </div>
     </div>
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->
@endsection

resources/views/admin/post/index.blade.php
@extends('layouts.admin_layout')
@section('title', 'Все статьи')
@section('content')

<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">Все статьи</h1>
        </div><!-- /.col -->
      </div><!-- /.row -->
      @if (session('success'))
            <div class="alert alert-success" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
            </div>
        @endif
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
            <div class="card">
                <div class="card-body p-0">
                  <table class="table table-striped projects">
                      <thead>
                          <tr>
                              <th style="width: 5%">
                                  ID
                              </th>
                              <th>
                                  Заголовок
                              </th>
                              <th>
                                  Категория
                              </th>
                              <th>
                                  Дата добавления
                              </th>
                              <th>
                                Статус
                              </th>
                              <th style="width: 30%">
                              </th>
                          </tr>
                      </thead>
                      <tbody>
                          @foreach ($posts as $post)
                          <tr>
                            <td>
                                {{ $post ['id'] }}
                            </td>
                            <td>
                                {{ $post ['title'] }}
                            </td>
                            <td>
                                {{ $post->category['title'] }}
                            </td>
                            <td>
                                {{ $post ['created_at'] }}
                            </td>
                            <td>
                                @if ($post->status == 1)
                                        Active
                                @elseif ($post->status == 0)
                                        Disable
                                @endif
                            </td>
                            <td class="project-actions text-right">
                                <a class="btn btn-info btn-sm" href="{{ route('post.edit', $post ['id']) }}">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Редактировать
                                </a>
                                <form action="{{ route('post.destroy', $post ['id']) }}" method="POST" style="display: inline-block">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger btn-sm delete-btn">
                                        <i class="fas fa-trash">
                                        </i>
                                        Удалить
                                    </button>
                                </form>
                            </td>
                        </tr>
                          @endforeach
                      </tbody>
                  </table>
                </div>
                <!-- /.card-body -->
              </div>
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->
@endsection